name: Start Dev Site
on:
  push:
    branches:
      - develop
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: yokobond/xcratch-example
          ref: develop
          path: ./xcratch-example
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./xcratch-example
          destination_dir: ./dev
          keep_files: true
