name: Start Site
on:
  push:
    branches:
      - master
    tags:
      - "!*"
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: yokobond/xcx-key-events
          ref: master
          path: ./xcx-key-events
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./xcx-key-events
          keep_files: true
